// Illustrations, not app screenshots or interactive app controls.
export function artwork(motif) {
  const illustrations = {
    receipt: `<div class="receipt"><div class="receipt-header"><span class="receipt-logo">P</span><strong>Your neighbourhood store</strong><span>Receipt preview</span></div><div class="receipt-row"><span>Notebook × 2</span><span>₹120</span></div><div class="receipt-row"><span>Paper clips × 1</span><span>₹40</span></div><div class="receipt-row total"><strong>Total</strong><strong>₹160</strong></div><div class="barcode" aria-hidden="true"></div><p>Thank you for shopping with us.</p></div><div class="paper-note">Create. Print. Carry on.</div>`,
    music: `<div class="record" aria-hidden="true"><div class="record-label">OneTap<br>Music</div></div><div class="music-library"><span>Your collection</span><strong>A soundtrack for<br>every kind of day.</strong><div class="music-tags"><span>Slow mornings</span><span>Deep focus</span><span>On the move</span></div><div class="waveform" aria-hidden="true">${Array.from({length: 25},(_,i)=>`<i style="--height:${18+((i*23)%58)}%"></i>`).join('')}</div><span>Organized by you.</span></div>`,
    map: `<div class="map-board"><svg class="map-roads" viewBox="0 0 500 470" aria-hidden="true"><path fill="#c8ddbf" d="M0 0h160l-20 120L0 165zm355 310 145-20v180H340z"/><path fill="none" stroke="#accfde" stroke-width="52" d="M430-30Q180 150 370 310t10 210"/><path fill="none" stroke="#fff" stroke-width="21" d="M-20 225 525 115M80-20 230 500M-10 385 540 240"/><path fill="none" stroke="#d0d8c5" stroke-width="2" d="M-20 225 525 115M80-20 230 500M-10 385 540 240"/></svg><div class="map-place home">Home</div><div class="map-place park">The park</div><div class="map-person person-one"><b>A</b><span>Alex</span></div><div class="map-person person-two"><b>S</b><span>Sam</span></div><div class="map-caption"><span class="status-dot"></span> A place for your people</div></div>`,
    work: `<div class="work-board"><div class="skill-tags"><span>Plumbing</span><span>Electrical</span><span>Carpentry</span></div><div class="job-sheet"><span class="job-icon" aria-hidden="true">⌁</span><span>A job to get done</span><h3>Make room for<br>the right skills.</h3><dl><div><dt>The work</dt><dd>Discuss the details</dd></div><div><dt>The rate</dt><dd>Agree together</dd></div><div><dt>The booking</dt><dd>Keep it in one place</dd></div></dl></div><div class="work-caption">For the hands that make it happen.</div></div>`,
    call: `<div class="call-orbit" aria-hidden="true"></div><div class="call-phone"><span class="phone-time">09:00</span><span class="call-kind">Scheduled reminder</span><div class="caller-avatar" aria-hidden="true">R</div><strong>Take a break</strong><p>A little time for yourself.</p><div class="call-wave" aria-hidden="true">((( &nbsp; ♪ &nbsp; )))</div><span class="call-footnote">A reminder, with a ring.</span></div>`,
    lab: `<div class="lab-board"><div class="lab-heading"><span class="lab-cross" aria-hidden="true">+</span><strong>Your lab-test details</strong></div><div class="lab-folder"><span>Tests</span><strong>Start with the details.</strong><div class="lab-line"></div><div class="lab-line short"></div></div><div class="lab-folder"><span>Bookings</span><strong>Keep your visit organized.</strong><div class="lab-line"></div><div class="lab-line short"></div></div><div class="lab-folder"><span>Reports</span><strong>Find what you need again.</strong><div class="lab-line"></div><div class="lab-line short"></div></div></div>`,
  };
  return illustrations[motif];
}
