// Product copy grounded in the app repositories and the existing public catalog.
// No store buttons until a release URL has been verified for that product.
export const products = [
  {
    slug: 'onetapmusic', name: 'OneTapMusic', category: 'A home for your music',
    headline: 'Your music.\nYour kind of order.',
    description: 'Keep your audio collection close. Organize tracks into personal categories and settle into listening with a built-in player.',
    accent: '#225874', mark: '♪', motif: 'music',
    featuresTitle: 'A collection that feels like yours.',
    features: [
      ['Make room for every mood', 'Create your own categories so your music is organized the way you think about it.'],
      ['Keep listening in one place', 'Move from your collection into the built-in player without switching apps.'],
      ['Bring your own audio', 'Import audio files you own or have permission to use and keep them in your personal library.'],
    ],
    steps: ['Add your audio', 'Organize your categories', 'Choose a track and listen'],
    question: 'Can I use music from any source?',
    answer: 'Only add audio that you own or are authorized to use. OneTapMusic is not a way to bypass a streaming service’s restrictions.',
    closing: 'Make space for your next favourite track.', cta: 'Ask about OneTapMusic',
    note: 'For your own audio and content you have permission to use.',
  },
  {
    slug: 'nestlink', name: 'NestLink', category: 'Family location sharing',
    headline: 'A little closer,\nwherever you are.',
    description: 'Bring your family together on one map. Share locations, send a quick ping, and stay in touch through the everyday comings and goings.',
    accent: '#215942', mark: '⌂', motif: 'map',
    featuresTitle: 'Less wondering. More connection.',
    features: [
      ['Your people, on one map', 'See shared family locations in a familiar map view.'],
      ['A quick way to check in', 'Send a ping when you want to get someone’s attention without a long conversation.'],
      ['Important places and alerts', 'Use place notifications and SOS alerts to help your linked family stay informed.'],
    ],
    steps: ['Invite your family', 'Set up location permissions', 'Stay connected on the map'],
    question: 'Does NestLink replace emergency services?',
    answer: 'No. SOS alerts help notify linked people; they do not replace calling local emergency services. Location and alerts depend on permissions, connectivity, and device settings.',
    closing: 'Keep your people a little closer.', cta: 'Ask about NestLink',
    note: 'Location sharing requires permission and a connection. Always respect the people you link with.',
  },
  {
    slug: 'labourchauk', catalogSlug: 'labourchawk', name: 'LabourChauk', category: 'Local skills. Real work.',
    headline: 'Good work starts\nwith the right person.',
    description: 'A place for people who need a job done and people with the skills to do it. Find workers, discuss the details, and manage bookings together.',
    accent: '#983e16', mark: 'L', motif: 'work',
    featuresTitle: 'From “who can help?” to a clear plan.',
    features: [
      ['Find the skill you need', 'Browse workers by skill, from plumbing and electrical work to carpentry.'],
      ['Agree on the details', 'Discuss the work and negotiate the rate before confirming a booking.'],
      ['Keep the job together', 'Follow bookings and use in-app chat to keep the conversation connected to the work.'],
    ],
    steps: ['Find a worker or post a job', 'Discuss the work and rate', 'Confirm and manage the booking'],
    question: 'Is this for workers or customers?',
    answer: 'Both. Customers can find skills and book work; workers can receive requests, discuss rates, and manage jobs. Contact us for current access and availability in your area.',
    closing: 'Find help. Find work. Get started.', cta: 'Ask about LabourChauk',
    note: 'Confirm the scope, rate, and availability with the other person before booking.',
  },
  {
    slug: 'printlabel', name: 'PrintLabel', category: 'Billing for small businesses',
    headline: 'From your counter\nto their hands.',
    description: 'Create an invoice, keep track of your bills, and print a receipt. PrintLabel brings customers, items, and everyday billing into one place.',
    accent: '#176778', mark: 'P', motif: 'receipt',
    featuresTitle: 'The small details that keep business moving.',
    features: [
      ['Make the right document', 'Create invoices, receipts, and quotations with your customers and line items.'],
      ['Know where every bill stands', 'Keep customer history, inventory, and bill status within reach.'],
      ['Print the way you work', 'Use supported Bluetooth printers on Android, network printing, or system printing and AirPrint.'],
    ],
    steps: ['Add your customer and items', 'Create an invoice or receipt', 'Print, share, or save as PDF'],
    question: 'Which printers can I use?',
    answer: 'Printer support depends on your device and printer model. Android supports compatible Bluetooth ESC/POS printers. iOS uses AirPrint or compatible network printing, not classic Bluetooth SPP. Ask us about your setup.',
    closing: 'Less paperwork between you and your customers.', cta: 'Ask about PrintLabel',
    note: 'Have a printer in mind? Include its model and your phone type when you contact us.',
  },
  {
    slug: 'ringreminder', name: 'RingReminder', category: 'Reminders with a familiar ring',
    headline: 'Give your next\nreminder a ring.',
    description: 'Turn a reminder into a scheduled, call-style alert. Choose a name, add your message, and set a time that fits your day.',
    accent: '#68408b', mark: 'R', motif: 'call',
    featuresTitle: 'A reminder that feels familiar.',
    features: [
      ['Put a name to it', 'Personalize the caller name and message so the reminder means something to you.'],
      ['Set it once or repeat it', 'Schedule a single reminder or use recurrence rules for your regular routines.'],
      ['Make it your own', 'Choose call-screen themes, use quick presets, or enter your reminder with voice input.'],
    ],
    steps: ['Write your reminder', 'Pick a time and theme', 'Get a call-style alert'],
    question: 'Does RingReminder make real phone calls?',
    answer: 'No. The incoming-call screen is a simulated reminder inside the app, not a real phone call. Alert delivery depends on notification, alarm, and battery settings.',
    closing: 'For the little things worth remembering.', cta: 'Ask about RingReminder',
    note: 'Call-style alerts are simulated reminders, not real calls or an emergency service.',
  },
  {
    slug: 'bloodlabs', name: 'Bloodlabs', category: 'Lab tests, bookings, and records',
    headline: 'Keep the details\nout of the way.',
    description: 'A simpler place to browse lab tests, manage patient details, and keep bookings and reports together.',
    accent: '#285c89', mark: '+', motif: 'lab',
    featuresTitle: 'The practical side of getting a lab test.',
    features: [
      ['Browse available tests', 'Find test information and keep your selections together before booking.'],
      ['Keep patient details organized', 'Manage patient profiles and addresses as part of the booking process.'],
      ['Find bookings and reports', 'Return to your orders and reports without starting your search again.'],
    ],
    steps: ['Browse tests', 'Add the patient and booking details', 'Return to orders and reports'],
    question: 'Can Bloodlabs diagnose a condition?',
    answer: 'No. The app helps organize lab-test bookings and records. Ask a qualified healthcare professional about test selection and the interpretation of any results.',
    closing: 'A clearer place for your lab-test details.', cta: 'Ask about Bloodlabs',
    note: 'For booking and record organization. Not a diagnosis or medical advice. Please do not send medical records by email.',
  },
];
